### ISSUE TITLE
Get to know pgadmin4 and postgreSQL

### ISSUE THREAD

**Issue by janis-rullis** [janis-rullis/sql#7]
http://pga.lm1.local/browser/

From https://github.com/Janis-Rullis-IT/flexi-tic-tac-toe/issues/42

## Tasks

* [x] Temp priv https://github.com/Janis-Rullis-IT/sql/issues/7#issuecomment-721687358
* [x] Seq. https://github.com/Janis-Rullis-IT/sql/issues/7#issuecomment-721737611
* [x] Backup DB.
* [x] Backup tab.
* [x] Create tab.
* [x] Tab comments.
* [x] Try indexes.
* [x] Explain and analyze.
* [x] Monitor queries.
* [x] Public user.
* [ ] Box columns https://www.postgresql.org/docs/13/release-13.html
* [ ] Incremental sorting.
* [ ] vacuuming.
* [ ] Maintenance
* [ ] Allow EXPLAIN, auto_explain, autovacuum, and pg_stat_statements to track WAL usage statistics 
* [x] read-only transaction mode 
* [x]  streaming replication
* [ ] Allow FETCH FIRST to use WITH TIES to return any additional rows that match the last result row 
* [ ] Add ALTER TABLE ... DROP EXPRESSION to allow removing the GENERATED property from a column
* [ ] Types. Add ALTER TYP
* [ ] JSON. Add alternate version of jsonb_set() wit
* [ ] NORMALIZE()
* [ ] Add function gen_random_uuid() to generate version-4 UUIDs
* [ ] Add function min_scale()
* [ ] Add function trim_scale() 
* [ ] Generate backup manifests for base backups, and verify them.
* [ ] A new tool pg_verifybackup can verify backups.
* [ ] Have pg_basebackup estimate the total backup size by defau

**Comment by janis-rullis** [comment]
# Temporary priv

![image](https://user-images.githubusercontent.com/17935810/98108561-d57ad980-1ea4-11eb-8acb-0f926f359f6d.png)

* [x] https://github.com/Janis-Rullis-IT/sql/blob/master/postgresql/Priveleges.md

**Comment by janis-rullis** [comment]
# Seq.

* [x] https://github.com/Janis-Rullis-IT/sql/blob/master/postgresql/Seq.md
